### ISSUE TITLE
Replace Express with uWebSocket

### ISSUE THREAD

**Issue by ansarizafar** [botmasterai/botmaster#16]
Consider replacing expressjs with uWebScket performance gain is huge https://github.com/uWebSockets/uWebSockets/wiki/(More-than)-one-million-requests-per-second-in-Node.js

A complete example of a Facebook messenger bot with wit.ai would greatly help new bot developers.

**Comment by jdwuarin** [comment]
That looks very interesting. Was planning on making changes regarding the server for v3. uWebSocket might be the one picked.

I'll be working on a wit.ai guide later this week. Hopefully that'll help.

**Comment by jdwuarin** [comment]
So looking some more at uWebSocket and it looks like it provides developers with a replacement http server. And theoretically should work with express. However, it doesn't as uWebSocket.http doesn't implement everything node's http server does. In this case, `listeners` don't seem to be implemented yet.
That alongside the fact that it is still in alpha make me say that it would be best to wait until it is more mature to replace the default server within botmaster.

Express is still used under the hood and the preferred way for now as it is so widely used and most node.js developers trying to implement their own bot class would know how to deal with a simple node router to add potential webhook routes.

I'll close this issue once the botmaster-wit.ai package and the accompanying guide is out.

**Comment by ansarizafar** [comment]
Agreed.

**Comment by jdwuarin** [comment]
Botmaster v3 does not have Express as a dependency anymore. It has just been merged to master and Documentation for it will come out shortly. Because it only relies on a server, It might even work with this.
