### ISSUE TITLE
Messenger settings

### ISSUE THREAD

**Issue by ansarizafar** [botmasterai/botmaster#19]
How can I perform following tasks with botmaster ?

1. Set Messenger thread settings (Greeting, Get Started button, Persistent menu).
2. Set Messenger on boarding hook.
3. White list domains for Messenger extensions sdk.

**Comment by jdwuarin** [comment]
Hi Ansari,

I am adding these and they will be made available in the next version of Botmaster coming in a few days. We will also be moving the bot classes out of botmaster core. So you will need to npm install these packages. All of the points mentioned here should be covered in that first version of `botmaster-mesenger`.

**Comment by ansarizafar** [comment]
That would be great. Please also add Account linking to the list of messenger features.

**Comment by jdwuarin** [comment]
Hi Ansari,

I saw that too. Those changes look awesome. I'll make sure to add them to the botmaster-messenger package asap.

**Comment by jdwuarin** [comment]
See the changes in `botmaster-messenger` for the latest changes
