### ISSUE TITLE
Wrong attachment example

### ISSUE THREAD

**Issue by bgbraga** [botmasterai/botmaster#30]
There is a wrong example of send attachment at base_bot.js
Is is also affecting the documentation site.

* @example
   * bot.sendAttachmentFrom**URL**To('image', "some image url you've got", update.sender.id);
   */
  sendAttachmentFrom**Url**To(type, url, recipientId, sendOptions) {

The "URL" camel case is wrong at example / documentation.

**Comment by clemens-tolboom** [comment]
This will be fixed by #31
