### ISSUE TITLE
telegram bot remains inactive on node-red

### ISSUE THREAD

**Issue by shivamgupta211** [botmasterai/botmaster#32]
I am having an issue on which i am using a telegram bot but remains inactive on node-red.
I have configured this node and filled all the details correctly and created the webhook on telegram and exposed my localhost using ngrok.

Any suggestions ?
![sketch](https://user-images.githubusercontent.com/17015995/29738888-8bb7ea3e-8a4d-11e7-8f9d-b966dafdf143.png)

**Comment by jwickens** [comment]
Hi Shiva node-red integration was a bit of an experiment and unfortunately they don't play very well. I'm going to close this, but feel free to participate in the node red repo for botmaster.
