### ISSUE TITLE
Support for voice stream?

### ISSUE THREAD

**Issue by IamLance** [botmasterai/botmaster#39]
Hi,

                             I would like to ask if this framework is applicable accepting voice inputs and chatbot returning voice output as well.

**Comment by jdwuarin** [comment]
Hi,

You would have to write your own bot class for that. I've tried it myself and didn't have any issues with it. If that makes sense, try taking a look at this doc: http://botmasterai.com/documentation/latest/working-with-botmaster/writing-your-own-bot-class.html. You can start straight from the `Creating your own bot classes` section
