### ISSUE TITLE
Is there any clearly document for integrating a new chat application into this project?

### ISSUE THREAD

**Issue by gitvani** [botmasterai/botmaster#41]
I am trying to create a project for LINE chat app by implementing from BaseBot.  After copy from MessengerBot and change something but I can not integrate it with botmaster. The request can not send to middleware controller. The problem maybe come from __setupServersRequestListeners() on botmaster.js: 

```
 for (const path in this.__serverRequestListeners) {
        if (req.url.indexOf(path) === 0) {
          const requestListener = this.__serverRequestListeners[path];
          return requestListener.call(this.server, req, res);
        }
      }
```
If I have 2 paths: messenger/webhook and line/webhook, only the first element of __serverRequestListeners can access to the if block.

Is there any clearly document for contribute a new chat application?

**Comment by jdwuarin** [comment]
Have you checked out the documentation for this: http://botmasterai.com/documentation/latest/working-with-botmaster/writing-your-own-bot-class.html

**Comment by jdwuarin** [comment]
Closing this as no reply.
