### ISSUE TITLE
bot.sendTextMessageTo less than sign not working

### ISSUE THREAD

**Issue by IamLance** [botmasterai/botmaster#42]
bot.sendTextMessageTo("<2", data.id) 

The "<2" is not being sent. It works with other strings but not with '<' sign partnered in front

**Comment by jdwuarin** [comment]
Are you using `botmaster-fulfill` with that? This could be the reason for it. Otherwise, it would be something on FB part like trying to parse html or something.

**Comment by IamLance** [comment]
yes we are using botmaster-fullfill and our front end is not FB its web based with socket. Any solution /workaround?

**Comment by jwickens** [comment]
Have you tried if `&lt` works on your target UI?

**Comment by IamLance** [comment]
@jwickens have tried your solution and it works. Thanks I guess we would have to map this one.

**Comment by jwickens** [comment]
That's great @IamLance A general solution will land in fulfil version 5.0.0, but you will need to use nodejs >= 9.0
