### ISSUE TITLE
Sending Files

### ISSUE THREAD

**Issue by willemevenwel** [botmasterai/botmaster#44]
hi,

im using the socketio bot.

i want to know if you have example of sending a file via the client to botmaster implimentation.

ive found and got the following package working in seperate project:
https://www.npmjs.com/package/socketio-file-upload

but want to know how i could use it with botmaster, or if botmaster has a implimentation to handle files/bytes/bytearray?

regards

willem

**Comment by willemevenwel** [comment]
_I wanted to mark this as feature and NOT issue_

**Comment by jdwuarin** [comment]
This is essentially the same question as: https://github.com/botmasterai/botmaster-socket.io/issues/7

Redirecting there and closing this issue now
