### ISSUE TITLE
Initial messages

### ISSUE THREAD

**Issue by JiProchazka** [botmasterai/botmaster#45]
Hi,

is it possible to send an initial message to the new coming user when he opens the messenger on Facebook?

I know Facebook allows this as you can send some chatbot introduction at the start.

Thanks

**Comment by jdwuarin** [comment]
Hey - this question would really be more suited for the: https://github.com/botmasterai/botmaster-messenger package. 

Either way, you can either do that by making the call to Facebook Messenger directly or by using the `_setGetStartedButton` method at start time when using your `facebook-messenger` bot

Hth
