### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by abhishekchotaliya** [botmasterai/botmaster#46]
Hi,
Just realized that the botmaster documentation is not accessible as of now.

**Url:** `http://botmasterai.com/documentation/latest`
**Error:** `ERR_EMPTY_RESPONSE`

**Comment by ebastidas** [comment]
Hi @jdwuarin, please could you share the documentation in any format? We really need it. Thanks a lot. :)

**Comment by jdwuarin** [comment]
Sorry about that guys. Just renewed the domain name. It's back up. In case that happens again, you can always find the documentation right on github here: https://github.com/botmasterai/botmasterai.github.io/tree/master/docs
